#!/bin/sh
### BEGIN INIT INFO
# Provides:          node
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Node.js - JavaScript runtime
# Description:       Starts/stops the Node.js daemon
### END INIT INFO

NAME=node
DAEMON=/usr/local/bin/node
DAEMON_OPTS="/etc/node/server.js"
PIDFILE=/run/node/node.pid
CONFIG=/etc/node/config.yaml
NODE_USER=node
NODE_GROUP=node
NODE_ENV=production
NODE_PORT=3000

set -e

. /lib/lsb/init-functions

test -x $DAEMON || exit 0
test -f $CONFIG || exit 0

mkdir -p /run/node /var/log/node /var/www/node
chown -R $NODE_USER:$NODE_GROUP /run/node /var/log/node /var/www/node

start() {
    log_daemon_msg "Starting $NAME" "$NAME"
    start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE \
        --chuid $NODE_USER:$NODE_GROUP --exec $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping $NAME" "$NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --signal TERM
    log_end_msg $?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|force-reload)
    $0 stop
    sleep 1
    $0 start
    ;;
  reload)
    $0 stop
    sleep 1
    $0 start
    ;;
  status)
    if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE") 2>/dev/null; then
      log_success_msg "$NAME is running (PID $(cat "$PIDFILE"))."
    else
      log_failure_msg "$NAME is not running."
      exit 1
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload|reload|status}"
    exit 1
    ;;
esac

exit 0