#!/bin/sh
### BEGIN INIT INFO
# Provides:          salt-minion
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SaltStack Minion
# Description:       SaltStack minion daemon
### END INIT INFO

NAME=salt-minion
DAEMON=/usr/bin/salt-minion
CONFIG=/etc/salt/minion
PIDFILE=/run/salt-minion.pid
USER=salt
GROUP=salt

[ -x "$DAEMON" ] || exit 0

. /lib/lsb/init-functions

start() {
    log_daemon_msg "Starting $NAME" "$NAME"
    mkdir -p /run/salt-minion /var/log/salt /var/cache/salt
    chown $USER:$GROUP /run/salt-minion /var/log/salt /var/cache/salt
    start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE \
        --chuid $USER:$GROUP --exec $DAEMON
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping $NAME" "$NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 5
    log_end_msg $?
}

reload() {
    log_daemon_msg "Reloading $NAME configuration" "$NAME"
    $DAEMON saltutil.refresh_all
    log_end_msg $?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac