#!/bin/sh
### BEGIN INIT INFO
# Provides:          krakend
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Krakend API Gateway
# Description:       Ultra-fast API Gateway built on Go
### END INIT INFO

NAME=krakend
DAEMON=/usr/local/bin/krakend
DAEMON_ARGS="run -d -c /etc/krakend/krakend.json"
CONFIG=/etc/krakend/krakend.json
USER=krakend
GROUP=krakend
PIDFILE=/var/run/${NAME}.pid

set -e

case "$1" in
  start)
    echo "Starting ${NAME}..."
    start-stop-daemon --start --quiet --chuid ${USER}:${GROUP} \
      --make-pidfile --pidfile ${PIDFILE} --background \
      --exec ${DAEMON} -- ${DAEMON_ARGS}
    echo "${NAME} started."
    ;;
  stop)
    echo "Stopping ${NAME}..."
    start-stop-daemon --stop --quiet --pidfile ${PIDFILE}
    rm -f ${PIDFILE}
    echo "${NAME} stopped."
    ;;
  restart|force-reload)
    $0 stop
    sleep 1
    $0 start
    ;;
  status)
    if [ -f ${PIDFILE} ]; then
      PID=$(cat ${PIDFILE})
      if kill -0 ${PID} 2>/dev/null; then
        echo "${NAME} is running (PID ${PID})."
      else
        echo "${NAME} is not running."
        exit 1
      fi
    else
      echo "${NAME} is not running."
      exit 1
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
