# Fluentd Configuration File
# http://docs.fluentd.org/

<source>
    @type forward
    port 24224
    bind 0.0.0.0
</source>

<match **>
    @type file
    path /var/log/fluentd/output
    flush 1
    log_level info
</match>

<match **>
    @type stdout
</match>