#!/bin/sh
### BEGIN INIT INFO
# Provides:          mattermost
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Mattermost Team Edition
# Description:       Open source chat platform
### END INIT INFO

NAME=mattermost
DAEMON=/opt/mattermost/mattermost
CONFIG=/etc/mattermost/settings.json
PIDFILE=/run/mattermost/mattermost.pid
USER=mattermost
GROUP=mattermost

[ -x "$DAEMON" ] || exit 0

. /lib/lsb/init-functions

start() {
    log_daemon_msg "Starting $NAME" "$NAME"
    mkdir -p /run/mattermost /var/mattermost /var/log/mattermost
    chown $USER:$GROUP /run/mattermost /var/mattermost /var/log/mattermost
    start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE \
        --chuid $USER:$GROUP --exec $DAEMON -- --config ${CONFIG}
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping $NAME" "$NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 5
    log_end_msg $?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        stop
        start
        ;;
    reload)
        ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
        ;;
esac