#!/bin/sh
### BEGIN INIT INFO
# Provides:          memcached
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Memcached Distributed Memory Caching System
# Description:       High-performance distributed memory caching system
### END INIT INFO

NAME=memcached
DAEMON=/usr/bin/memcached
CONFIG=/etc/memcached.conf
PIDFILE=/run/memcached/memcached.pid
USER=memcached
GROUP=memcached

[ -x "$DAEMON" ] || exit 0

. /lib/lsb/init-functions

start() {
    log_daemon_msg "Starting $NAME" "$NAME"
    mkdir -p /run/memcached /var/lib/memcached /var/log/memcached
    chown $USER:$GROUP /run/memcached /var/lib/memcached /var/log/memcached
    start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE \
        --chuid $USER:$GROUP --exec $DAEMON -- -u memcached -l 127.0.0.1 -p 11211 -m 64 -c 1024 -v
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping $NAME" "$NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 5
    log_end_msg $?
}

reload() {
    log_daemon_msg "Reloading $NAME configuration" "$NAME"
    # Memcached reload via signal
    start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --retry 2
    log_end_msg $?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac