#!/bin/sh
### BEGIN INIT INFO
# Provides:          litellm
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: LiteLLM - Unified LLM API Proxy
# Description:       LiteLLM provides a unified API for accessing multiple LLM providers
### END INIT INFO

NAME=litellm
DESC="LiteLLM - Unified LLM API Proxy"
DAEMON=/usr/local/bin/litellm
DAEMON_ARGS="--config /etc/litellm/config.yaml --host 0.0.0.0 --port 4000"
USER=litellm
GROUP=litellm
PIDFILE=/var/run/litellm/litellm.pid
LOGFILE=/var/log/litellm/litellm.log

# Source function library
. /lib/lsb/init-functions

start() {
    log_daemon_msg "Starting $DESC" "$NAME"
    if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE) 2>/dev/null; then
        log_progress_msg "already running"
        log_end_msg 0
        return 0
    fi
    
    mkdir -p /var/run/litellm /var/log/litellm
    chown $USER:$GROUP /var/run/litellm /var/log/litellm
    
    start-stop-daemon --start --quiet --background \
        --pidfile $PIDFILE --make-pidfile \
        --chuid $USER:$GROUP \
        --exec $DAEMON -- $DAEMON_ARGS >> $LOGFILE 2>&1
    
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping $DESC" "$NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 30
    log_end_msg $?
    rm -f $PIDFILE
}

status() {
    status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload|status}"
        exit 1
        ;;
esac

exit 0