#!/bin/sh
### BEGIN INIT INFO
# Provides:          semaphore
# Required-Start:    $network $remote_fs $syslog mysql postgresql
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Semaphore UI - Ansible/Terraform Automation Platform
# Description:       Web-based automation platform for Ansible and Terraform
### END INIT INFO

NAME=semaphore
DAEMON=/usr/local/bin/semaphore
CONFIG=/etc/semaphore/config.json
PIDFILE=/run/semaphore/semaphore.pid
USER=semaphore
GROUP=semaphore

[ -x "$DAEMON" ] || exit 0

. /lib/lsb/init-functions

start() {
    log_daemon_msg "Starting $NAME" "$NAME"
    mkdir -p /run/semaphore /var/lib/semaphore /var/log/semaphore
    chown $USER:$GROUP /run/semaphore /var/lib/semaphore /var/log/semaphore
    start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE \
        --chuid $USER:$GROUP --exec $DAEMON -- server --config $CONFIG
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping $NAME" "$NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 5
    log_end_msg $?
}

reload() {
    log_daemon_msg "Reloading $NAME configuration" "$NAME"
    kill -HUP $(cat $PIDFILE) 2>/dev/null || true
    log_end_msg $?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        stop
        start
        ;;
    reload)
        reload
        ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON $NAME
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
        ;;
esac