#!/bin/sh
### BEGIN INIT INFO
# Provides:          microk8s
# Required-Start:    $network $remote_fs $syslog snapd
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: MicroK8s Kubernetes
# Description:       Low-ops minimal production Kubernetes from Canonical
### END INIT INFO

NAME=microk8s
DAEMON=/usr/bin/microk8s

[ -x "$DAEMON" ] || exit 0

. /lib/lsb/init-functions

case "$1" in
    start)
        log_daemon_msg "Starting $NAME" "$NAME"
        $DAEMON start
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping $NAME" "$NAME"
        $DAEMON stop
        log_end_msg $?
        ;;
    restart|force-reload)
        $DAEMON stop
        $DAEMON start
        ;;
    status)
        $DAEMON status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
