#!/bin/sh
### BEGIN INIT INFO
# Provides:          docker
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Docker Application Container Engine
# Description:       Docker is a platform to build and run containers
### END INIT INFO

NAME=docker
DAEMON=/usr/bin/dockerd
PIDFILE=/var/run/docker.pid
CONFIG=/etc/docker/daemon.json

[ -x "$DAEMON" ] || exit 0

. /lib/lsb/init-functions

start() {
    log_daemon_msg "Starting $NAME" "$NAME"
    mkdir -p /var/lib/docker /run/docker
    start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE \
        --exec $DAEMON -- --config-file $CONFIG --pidfile $PIDFILE
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping $NAME" "$NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in
    start)   start ;;
    stop)    stop ;;
    restart|force-reload) stop; start ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
