# Fluent Bit Configuration File
# http://fluentbit.fluentd.org/

[SERVICE]
    flush         1
    daemon        off
    log_level     info
    log_file      /var/log/fluent-bit/fluent-bit.log
    pid_file      /run/fluent-bit/fluent-bit.pid
    storage_type memory

[OUTPUT]
    name          s3
    match         *
    bucket        my-fluent-bit-bucket
    buffer_chunk_limit 1MB
    total_limit_size 100MB
    auth_key      YOUR_AWS_ACCESS_KEY_ID
    secret_key    YOUR_AWS_SECRET_ACCESS_KEY
    region        us-east-1

[OUTPUT]
    name          file
    match         *
    path          /var/log/fluent-bit/output
    flush         1
    sync          true