#!/bin/sh
### BEGIN INIT INFO
# Provides:          traefik
# Required-Start:    $network $syslog docker
# Required-Stop:     $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Traefik reverse proxy
# Description:       Traefik - modern HTTP reverse proxy and load balancer
### END INIT INFO

NAME=traefik
DAEMON=/usr/local/bin/traefik
DAEMON_ARGS="--configFile=/etc/traefik/traefik.yml"
RUNAS_USER=traefik
RUNAS_GROUP=traefik
PIDFILE=/var/run/traefik.pid
LOGFILE=/var/log/traefik/traefik.log

set -e

. /lib/lsb/init-functions

start() {
    log_begin_msg "Starting $NAME"
    if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE") 2>/dev/null; then
        log_progress_msg "$NAME is already running"
        log_end_msg 0
        return 0
    fi
    start-stop-daemon --start --quiet \
        --chuid "$RUNAS_USER:$RUNAS_GROUP" \
        --background --make-pidfile --pidfile "$PIDFILE" \
        --exec "$DAEMON" -- $DAEMON_ARGS >> "$LOGFILE" 2>&1
    log_end_msg $?
}

stop() {
    log_begin_msg "Stopping $NAME"
    start-stop-daemon --stop --quiet --pidfile "$PIDFILE" --retry=TERM/3/KILL/5
    rm -f "$PIDFILE"
    log_end_msg $?
}

restart() {
    stop
    sleep 1
    start
}

status() {
    if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE") 2>/dev/null; then
        echo "$NAME is running (PID: $(cat $PIDFILE))"
        return 0
    else
        echo "$NAME is not running"
        return 3
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        restart
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload|status}"
        exit 3
        ;;
esac

exit 0
