#!/bin/sh
### BEGIN INIT INFO
# Provides:          redis
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Redis In-Memory Data Structure Store
# Description:       In-memory data structure store, used as a database, cache, and message broker
### END INIT INFO

NAME=redis
DAEMON=/usr/bin/redis-server
CONFIG=/etc/redis/redis.conf
PIDFILE=/run/redis/redis.pid
USER=redis
GROUP=redis

[ -x "$DAEMON" ] || exit 0

. /lib/lsb/init-functions

start() {
    log_daemon_msg "Starting $NAME" "$NAME"
    mkdir -p /run/redis /var/lib/redis /var/log/redis
    chown $USER:$GROUP /run/redis /var/lib/redis /var/log/redis
    start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE \
        --chuid $USER:$GROUP --exec $DAEMON -- /etc/redis/redis.conf
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping $NAME" "$NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 5
    log_end_msg $?
}

reload() {
    log_daemon_msg "Reloading $NAME configuration" "$NAME"
    $DAEMON /etc/redis/redis.conf --reconfig
    log_end_msg $?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac