#!/bin/sh
### BEGIN INIT INFO
# Provides:          caddy
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Caddy HTTP/2 Web Server
# Description:       Caddy is an open source web server with automatic HTTPS
### END INIT INFO

NAME=caddy
DAEMON=/usr/bin/caddy
CONFIG=/etc/caddy/Caddyfile
PIDFILE=/run/caddy/caddy.pid
USER=caddy
GROUP=caddy

[ -x "$DAEMON" ] || exit 0

. /lib/lsb/init-functions

start() {
    log_daemon_msg "Starting $NAME" "$NAME"
    mkdir -p /run/caddy /var/lib/caddy /var/log/caddy
    chown $USER:$GROUP /run/caddy /var/lib/caddy /var/log/caddy
    start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE \
        --chuid $USER:$GROUP --exec $DAEMON -- run --environ --config $CONFIG
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping $NAME" "$NAME"
    $DAEMON stop --config $CONFIG
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 5
    log_end_msg $?
}

reload() {
    log_daemon_msg "Reloading $NAME configuration" "$NAME"
    $DAEMON reload --config $CONFIG --force
    log_end_msg $?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        stop
        start
        ;;
    reload)
        reload
        ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
        ;;
esac