#!/bin/sh
### BEGIN INIT INFO
# Provides:          haproxy
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: HAProxy Load Balancer
# Description:       HAProxy is a high-performance load balancer
### END INIT INFO

NAME=haproxy
DAEMON=/usr/sbin/haproxy
CONFIG=/etc/haproxy/haproxy.cfg
PIDFILE=/run/haproxy.pid
USER=haproxy
GROUP=haproxy

[ -x "$DAEMON" ] || exit 0

. /lib/lsb/init-functions

start() {
    log_daemon_msg "Starting $NAME" "$NAME"
    mkdir -p /run/haproxy /var/lib/haproxy /var/log/haproxy
    chown -R $USER:$GROUP /run/haproxy /var/lib/haproxy /var/log/haproxy
    start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE \
        --chuid $USER:$GROUP --exec $DAEMON -- -f $CONFIG -D -p $PIDFILE
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping $NAME" "$NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 5
    log_end_msg $?
}

reload() {
    log_daemon_msg "Reloading $NAME configuration" "$NAME"
    kill -USR2 $(cat $PIDFILE 2>/dev/null) 2>/dev/null || true
    log_end_msg $?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        stop
        start
        ;;
    reload)
        reload
        ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
        ;;
esac