#!/bin/sh
### BEGIN INIT INFO
# Provides:          envoy
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Envoy Proxy
# Description:       Envoy is a high-performance proxy
### END INIT INFO

NAME=envoy
DAEMON=/usr/local/bin/envoy
CONFIG=/etc/envoy/envoy.yaml
PIDFILE=/run/envoy/envoy.pid
USER=envoy
GROUP=envoy

[ -x "$DAEMON" ] || exit 0

. /lib/lsb/init-functions

start() {
    log_daemon_msg "Starting $NAME" "$NAME"
    mkdir -p /run/envoy /var/log/envoy
    chown $USER:$GROUP /run/envoy /var/log/envoy
    start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE \
        --chuid $USER:$GROUP --exec $DAEMON -- -c $CONFIG --service-node $(hostname) --service-cluster envoy
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping $NAME" "$NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 5
    log_end_msg $?
}

reload() {
    log_daemon_msg "Reloading $NAME" "$NAME"
    kill -HUP $(cat $PIDFILE 2>/dev/null) 2>/dev/null || true
    log_end_msg $?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        stop
        start
        ;;
    reload)
        reload
        ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
        ;;
esac